config/routes.rb
Rails.application.routes.draw do
  
  resources :members
  devise_for :admins, :controllers => { :registrations => "admin/registrations"}
  devise_for :users ,:controllers => { :registrations => "registrations" }
  
  resources :templates
  resources :groups do
    member do
      get 'remainders'
    end
  end
  
  get "mass_sms/import_csv" => "members#import_csv"
  resources :members do 
    collection do
      post :import
    end
  end
  
  namespace :admin do
    get "/profile" => "pages#profile"
    resources :users, only: [:index, :show, :destroy] do
      member do
        get :approve
        get :reject
      end 
    end
    resources :admin, only: [:update_profile] do 
      put :update_profile, on: :member, as: :update_profile
    end
    resources :groups, only: [:index] do 
      member do
        get :approve
        get :reject
      end 
    end
  end

  get '/admin' => 'admin/pages#index'
  get '/home' => 'pages#home'
  post "/search" => 'pages#search'

  root to: 'pages#index'

end

app/views/templates/_form.html.erb
<%= form_for(@template, html: { class: 'form-horizontal'}) do |f| %>
	<div class="form-group">
    <%= f.label "Name", class: "control-label col-xs-3"%>
    <div class="col-xs-6">
      <%= f.text_field :name, :class => "form-control",  placeholder: "Enter name"%>
    </div>  
  </div>

  <div class="form-group">
    <%= label_tag "Insert Merge Field", nil, class: "control-label col-xs-3"%>
    <div class="col-xs-6">
      <%= select_tag 'template_variable_options',
              options_for_select([["Name","{name}" ], ["last_name", "{last_name}"], ["mobile", "{mobile}"]]),
              class: 'sms_template_variable_select form-control', prompt: '--- Insert Merge Field ---' %>
    </div>
      <button class="btn btn-success" onClick="appendTemplateVariableToSmsTemplate()" type="button">Add</button>
   <!--  <div class="col-sx-3">
          </div>
    </div> -->
  </div>
  
  <div class="form-group">
    <%= f.label "Text", class: "control-label col-xs-3 puu-right"%>
    <div class="col-xs-6">
      <%= f.text_area :message, :class => "form-control sms_template_content" , id: "textarea1",  placeholder: "Enter predefined SMS text"%>
      <p class="help-block">
        <span class="content_length">125</span>
        characters /
        <span class="credit_count">1</span>
        credit (approx - using variables can affect message length)
      </p>
    </div>  
  </div>
  <%= f.hidden_field :user_id, value: current_user.id %>  
  

    


  <div class = "form-group text-center">

    <%= f.submit class: "btn btn-success" %>
  </div> <br>
<% end %>

app/views/templates/edit.html.erb
<div class="box">
	<div class="box-header">
		<h3 class="box-title">Update Template</h3>
		<%= link_to 'New Template', new_template_path, style: "float: right", class: "btn btn-success btn-sm" %>
	</div>
	<div class="box-body no-padding users">
		<%= render 'form' %>
	</div>
</div>

app/views/templates/index.html.erb
<div class="box">
  <div class="box-header">
    <h3 class="box-title">Templates</h3>
    <%= link_to 'New Template', new_template_path, style: "float: right", class: "btn btn-success btn-sm" %>
  </div>
  <div class="box-body no-padding users">
    <table class= "table table-condensed">
    <thead>
      <tr>
        <th>Name</th>
        <th>Message</th>
        <th colspan="1"></th>
      </tr>
    </thead>

    <tbody>
      <% @templates.each do |template| %>
        <tr>
          <td><%= template.name %></td>
          <td><%= template.message %></td>
          <!-- <td>
            <%#= link_to template  do %>
              <%#= show_icon %>
            <%# end %>
          </td> -->
          <td>
            <%= link_to edit_template_path(template), class: "badge bg-green" do %>
              <%= "Edit" %>
            <% end %>
          </td>
          <!-- <td>
            <%#= link_to template, method: :delete, data: { confirm: 'Are you sure?' } do %>
              <%#= delete_icon %>
            <%# end %>
            </td> -->
        </tr>
      <% end %>
    </tbody>
    </table>
  </div>
</div>

app/views/templates/new.html.erb
<div class="box box-success">
	<div class="box-header">
		<h3 class="box-title">Create New Template</h3>
		<%= link_to 'All Templates', templates_path, style: "float: right", class: "btn btn-success btn-sm" %>
	</div>
	<div class="box-body no-padding">
		<%= render 'form' %>
	</div>
</div>

app/views/templates/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @template.name %>
</p>

<p>
  <strong>Message:</strong>
  <%= @template.message %>
</p>

<%= link_to 'Edit', edit_template_path(@template) %> |
<%= link_to 'Back', templates_path %>