config/routes.rb
Rails.application.routes.draw do
  
  resources :members
  devise_for :admins, :controllers => { :registrations => "admin/registrations"}
  devise_for :users ,:controllers => { :registrations => "registrations" }
  
  resources :templates
  resources :groups do
    member do
      get 'remainders'
    end
  end
  
  get "mass_sms/import_csv" => "members#import_csv"
  resources :members do 
    collection do
      post :import
    end
  end
  
  namespace :admin do
    get "/profile" => "pages#profile"
    resources :users, only: [:index, :show, :destroy] do
      member do
        get :approve
        get :reject
      end 
    end
    resources :admin, only: [:update_profile] do 
      put :update_profile, on: :member, as: :update_profile
    end
    resources :groups, only: [:index] do 
      member do
        get :approve
        get :reject
      end 
    end
  end

  get '/admin' => 'admin/pages#index'
  get '/home' => 'pages#home'
  post "/search" => 'pages#search'

  root to: 'pages#index'

end

app/models/group.rb
class Group < ActiveRecord::Base
  belongs_to :user
  
  default_scope { order('created_at') }

  INTERVAL = [30, 60, 90, 120]

  def group_status
    status ? "approved" : "pending"
  end

  def active_members
    user.members.where('id in (?)', members)
  end

  def option_members
    user.members.map {|member| [member.name, member.id] }
  end

  def selected_members
    active_members.map { |member| member.id }
  end

  def option_templates
    user.templates.map {|template| [template.name, template.id] }
  end

  def template
    Template.find_by(id: template_id)
  end

  def Group.todays_send_messages
    start_date = DateTime.now.beginning_of_day.in_time_zone
    end_date = DateTime.now.end_of_day.in_time_zone
    current_datetime = DateTime.now.in_time_zone
    groups = Group.where("renew_date between (?) and (?)", start_date, end_date )
    groups.each do |group|
      group.active_members.each do |member|
        elapsed_seconds = (group.renew_date - current_datetime).to_i
        elapsed_minutes = elapsed_seconds / 60
        member.send_message elapsed_minutes
      end
      group.update(renew_date: group.renew_date + group.interval.days)
    end
  end

end

app/controllers/admin/groups_controller.rb
class Admin::GroupsController < AdminController
  before_action :set_group, only: [:reject, :approve]

  def index
    @groups = Group.all
  end

  def reject
    @group.update(status: false)
    @groups = Group.all
  end

  def approve
    @group.update(status: true)
    @groups = Group.all
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_group
      @group = Group.find(params[:id])
    end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :authenticate_user!
  layout 'admin'
  before_action :set_group, only: [:show, :edit, :update, :destroy, :remainders]

  # GET /groups
  # GET /groups.json
  def index
    @groups = current_user.groups
  end

  # GET /groups/1
  # GET /groups/1.json
  def show
    # current_admin = Admin.first
    # sign_in current_admin
  end

  # GET /groups/new
  def new
    @group = current_user.groups.build
    # @group.remainders.build
  end

  # GET /groups/1/edit
  def edit
  end

  # POST /groups
  # POST /groups.json
  def create
    @group = Group.new(group_params)
    respond_to do |format|
      if @group.save
        format.html { redirect_to groups_path, notice: 'Group was successfully created.' }
        format.json { render :show, status: :created, location: @group }
      else
        format.html { render :new }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /groups/1
  # PATCH/PUT /groups/1.json
  def update
    respond_to do |format|
      if @group.update(group_params)
        format.html { redirect_to groups_path, notice: 'Group was successfully updated.' }
        format.json { render :show, status: :ok, location: @group }
      else
        format.html { render :edit }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /groups/1
  # DELETE /groups/1.json
  def destroy
    @group.destroy
    respond_to do |format|
      format.html { redirect_to groups_url, notice: 'Group was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def remainders
    @remainders = @group.remainders
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_group
      @group = Group.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through. members_attributes
    def group_params
      params[:group][:members] = params[:group][:members].reject(&:empty?)
      params.require(:group).permit(:name, :start_date, :time_stamp, :interval, :status, :user_id, :template_id, members: [] )
    end
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/views/groups/_form.html.erb
<%= form_for(@group, html: { class: "form-horizontal"} )do |f| %>
  
  <div class="form-group">
    <%= f.label "Group Name", class: "control-label col-xs-3"%>
    <div class="col-xs-6">
      <%= f.text_field :name, :class => "form-control",  placeholder: "Enter Group name"%>
    </div>  
  </div>

  <div class="form-group">
    <%= f.label "Select Start Date", class: "control-label col-xs-3"%>
    <div class="col-xs-3">
      <div class="input-group date">
        <div class="input-group-addon">
          <i class="fa fa-calendar"></i>
        </div>
        <%= f.text_field :start_date, class: "form-control pull-right",  placeholder: "Select Start Date", id: "datepicker", value: @group.start_date.try(:strftime, "%d-%m-%Y") %>
      </div>
    </div>
    <div class = "col-xs-3">
      <div class="input-group">
        <%= f.text_field :time_stamp, class: "form-control timepicker" %>
        <div class="input-group-addon">
          <i class="fa fa-clock-o"></i>
        </div>
      </div>
    </div>
  </div>

  <div class="form-group">
    <%= f.label "Schedule Event days", class: "control-label col-xs-3"%>
    <div class="col-xs-6">
      <%= f.select :interval, options_for_select(Group::INTERVAL), {}, 
      { class: "form-control", data: { placeholder: "Select SMS template"} }   %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label "Select Template", class: "control-label col-xs-3"%>
    <div class="col-xs-6">
     <%= f.select :template_id, options_for_select(@group.option_templates), {}, { class: "form-control", data: { placeholder: "Select SMS template"} }   %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label "Members", class: "control-label col-xs-3"%>
    <div class="col-md-6">

    <%= f.select :members, options_for_select(@group.option_members, 
      selected: @group.selected_members), {}, 
      { class: "form-control select2", multiple: 'multiple', data: { placeholder: "Select Members to add in group"} }   %>
    </div>

    <%= f.hidden_field :user_id, value: current_user.id %>
  </div>

  <div class="text-center">
    <%= f.submit class: "btn btn-success" %>
  </div>
  <br>
<% end %> 

 

<script type="text/javascript">
$(document).ready(function(){
  $(".select2").select2();

  $('#datepicker').datepicker({
    autoclose: true,
    format: 'dd-mm-yyyy'
  });

  $(".timepicker").timepicker();
});
</script>

app/views/groups/_groups.html.erb
<table id="groups" class="table table-condensed">
  <thead>
    <tr>
      <th>Name</th>
      <th> Start Date </th>
      <th> Interval </th>
      <th> Status</th>
      <th> Action</th>
     <!--  <th> Action</th> -->
    </tr>
  </thead>
  <tbody>
    <% @groups.each do |group| %>
    <tr>
      <td><%= link_to group.name.titleize, group_path(group) %></td>
       <td><%= group.start_date %></td>
        <td><%= group.interval %></td>
      <td><%= group.status %></td>
      <td><%= link_to "Edit", edit_group_path(group), class: "badge bg-green" %></td>
      <!-- <td><%#= link_to delete_icon, group, method: :delete, data: { confirm: 'Are you sure?'} %> -->
      </td>
    </tr>
    <% end %>
  </tbody>
</table>

app/views/groups/edit.html.erb
<div class="box">
  <div class="box-header">
    <h3 class="box-title">Editing Group</h3>
  </div>
  <div class="box-body no-padding">
    <%= render 'form' %>
  </div>
</div>

app/views/groups/index.html.erb
<div class="box">
  <div class="box-header">
    <h3 class="box-title">Groups</h3>
    <%= link_to 'New Group', new_group_path, style: "float: right", class: "btn btn-success btn-sm" %>
  </div>
  <div class="box-body no-padding users">
    <%= render 'groups' %>
  </div>
</div>

app/views/groups/new.html.erb
<div class="box box-success">
	<div class="box-header">
		<h3 class="box-title">Create New Group</h3>
	</div>
	<div class="box-body no-padding">
		<%= render 'form' %>
	</div>
</div>

app/views/groups/show.html.erb
<div class ="container">
	<p>
	  <strong>Name:</strong>
	  <%= @group.name %>
	</p>
	
	<p>
	  <strong>Status:</strong>
	  <%= @group.status %>
	</p>
	
	<p>
	  <strong>User:</strong>
	  <%= @group.user %>
	</p>
	
<div>