config/routes.rb
Rails.application.routes.draw do
  
  resources :members
  devise_for :admins, :controllers => { :registrations => "admin/registrations"}
  devise_for :users ,:controllers => { :registrations => "registrations" }
  
  resources :templates
  resources :groups do
    member do
      get 'remainders'
    end
  end
  
  get "mass_sms/import_csv" => "members#import_csv"
  resources :members do 
    collection do
      post :import
    end
  end
  
  namespace :admin do
    get "/profile" => "pages#profile"
    resources :users, only: [:index, :show, :destroy] do
      member do
        get :approve
        get :reject
      end 
    end
    resources :admin, only: [:update_profile] do 
      put :update_profile, on: :member, as: :update_profile
    end
    resources :groups, only: [:index] do 
      member do
        get :approve
        get :reject
      end 
    end
  end

  get '/admin' => 'admin/pages#index'
  get '/home' => 'pages#home'
  post "/search" => 'pages#search'

  root to: 'pages#index'

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :groups, dependent: :destroy
  has_many :members, dependent: :destroy
  has_many :templates, dependent: :destroy

  scope :pending_users, ->{ where(status: 'pending') }
  scope :order_by_created_at, ->{ order(created_at: :desc) }

  STATUS = ['pending', 'approved', 'blocked']
  def approved?
  	status == "approved"
  end

  def blocked?
  	status == "blocked"
  end

  def active_for_authentication?
  	super && approved? 
  end

  def inactive_message
  	return :blocked if blocked?
  	unless approved?
  	  :not_approved
  	else
  	  super
  	end
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < AdminController
  before_action :set_admin_user, only: [:show, :destroy, :approve, :reject, :update_profile]
  def index
    @users = User.order_by_created_at
  end

  def show
    @groups = @user.groups
  end

  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to admin_users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def approve
    @user.update(status: 'approved')
    @users = User.order_by_created_at
  end

  def reject
    @user.update(status: 'blocked')
    @users = User.order_by_created_at
  end

  def update_profile
    @user.update(admin_param)
    binding.pry
    redirect_to admin_path
  end

  private
    def set_admin_user
      @user = User.find(params[:id])
    end
    def admin_param
      params.require(:admin).permit(:name, :email, :mobile_no)
    end
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
	def status_class status
		case status
		when "blocked"
			"text-danger"
		when "pending"
			"text-danger"
		when "approved"
			"text-success"
		end
	end
end

app/views/admin/users/_form.html.erb
<%= form_for(@admin, url: update_profile_admin_admin_path(@admin), html: { class: "form-horizontal"},  method: :put ) do |f| %>

<form class="form-horizontal">
  <div class="form-group">
    <label for="inputName" class="col-sm-2 control-label">Name</label>

    <div class="col-sm-10">
       <%= f.text_field :name, :class => "form-control",  placeholder: "Name"%>
    </div>
  </div>
  <div class="form-group">
    <label for="inputEmail" class="col-sm-2 control-label">Email</label>

    <div class="col-sm-10">
      <%= f.text_field :email, :class => "form-control",  placeholder: "Email" %>
    </div>
  </div>
  <div class="form-group">
    <label for="inputName" class="col-sm-2 control-label">Contact</label>

    <div class="col-sm-10">
     <%= f.text_field :mobile_no, :class => "form-control",  placeholder: "Mobile no"%>
    </div>
  </div>

  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <%= f.submit class: "btn btn-success"%>
    </div>
  </div>
<% end %>

app/views/admin/users/_users.html.erb
<table class="table table-condensed user">
  <tr>
    <th>#</th>
    <th>Name</th>
    <th>Email</th>
    <th>Contact</th>
    <th> Joining date </th>
    <th> Status</th>
    <th> #Action </th>
  </tr>

  <% @users.each_with_index do |user, index| %>
  <tr>
    <td><%= index + 1 %></td>
    <td><%= user.name.try(:capitalize) %></td>
    <td><%= user.email %></td>
    <td><%= user.mobile_no %></td>
    <td><%= user.created_at.try(:strftime, "%d %B %Y - %l:%M %p") %></td>
    <td><span class="<%= status_class user.status %>"><%= user.status.try(:capitalize) %></span></td>
    <td>
      <%= link_to 'Block', reject_admin_user_path(user), class: "badge bg-red", remote: true %>
      <%= link_to 'Approve', approve_admin_user_path(user), class: "badge bg-green", remote: true  %>
    </td>
  </tr>
  <% end %>
</table>  

app/views/admin/users/approve.js.erb
$('.users').html("<%= j render(:partial => 'admin/users/users') %>");

app/views/admin/users/index.html.erb
<div>  
  <h1 class="title">Listing Users</h1>
  <table class="table table-bordered">
    <thead>
      <tr>
        <th>Email</th>
        <th>First name</th>
        <th>Last name</th>
        <th>Mobile no</th>
        <th>Address</th>
        <th colspan="2">Action</th>
      </tr>
    </thead>

    <tbody>
      <% @users.each do |user| %>
        <tr>
          <td><%= user.email %></td>
          <td><%= user.first_name %></td>
          <td><%= user.last_name %></td>
          <td><%= user.mobile_no %></td>
          <td><%= user.address %></td>
          <td><%= link_to show_icon, admin_user_path(user) %></td>
          <td><%= link_to delete_icon, admin_user_path(user), method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/admin/users/reject.js.erb
$('.users').html("<%= j render(:partial => 'users') %>");

app/views/admin/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<p>
  <strong>First name:</strong>
  <%= @user.first_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @user.last_name %>
</p>

<p>
  <strong>Mobile no:</strong>
  <%= @user.mobile_no %>
</p>

<p>
  <strong>Address:</strong>
  <%= @user.address %>
</p>

<%= render 'groups/groups' %>


<%= link_to 'Back', admin_users_path %>