config/routes.rb
Rails.application.routes.draw do
  
  resources :members
  devise_for :admins, :controllers => { :registrations => "admin/registrations"}
  devise_for :users ,:controllers => { :registrations => "registrations" }
  
  resources :templates
  resources :groups do
    member do
      get 'remainders'
    end
  end
  
  get "mass_sms/import_csv" => "members#import_csv"
  resources :members do 
    collection do
      post :import
    end
  end
  
  namespace :admin do
    get "/profile" => "pages#profile"
    resources :users, only: [:index, :show, :destroy] do
      member do
        get :approve
        get :reject
      end 
    end
    resources :admin, only: [:update_profile] do 
      put :update_profile, on: :member, as: :update_profile
    end
    resources :groups, only: [:index] do 
      member do
        get :approve
        get :reject
      end 
    end
  end

  get '/admin' => 'admin/pages#index'
  get '/home' => 'pages#home'
  post "/search" => 'pages#search'

  root to: 'pages#index'

end

app/models/member.rb
class Member < ActiveRecord::Base
	require 'csv'
	belongs_to :user

	def self.import(file, user_id)
		begin
			CSV.foreach(file.path, headers: true) do |row|
				row = row.to_h
				member = Member.find_or_initialize_by(contact: row['contact'], user_id: user_id)
				member.name = row['name']
				member.save
			end
		rescue Exception => e
			false
		end
		true
	end

	def send_message elapsed_minutes
    begin
      request = Clickatellsend::Request.new
      message = request.send_msg(to: contact, text: "I don't know", deliv_time: elapsed_minutes)
      puts ".................. message send successfully ................"
      status = request.get_msg_status(:apimsgid => message["ID"])
    rescue Exception => e
      "Error occured ..."
    end
  end

  # def User.send_messages
  #   start_date = DateTime.now.beginning_of_day.in_time_zone
  #   end_date = DateTime.now.end_of_day.in_time_zone
  #   current_datetime = DateTime.now.in_time_zone
  #   users = User.where("renew_date between (?) and (?)", start_date, end_date )
  #   users.each do |user|
  #     scheduled_date = user.renew_date
  #     scheduled_interval = 1
  #     elapsed_seconds = (scheduled_date - current_datetime).to_i
  #     elapsed_minutes = elapsed_seconds / 60
  #     # binding.pry
  #     user.send_message elapsed_minutes
  #     user.update(renew_date: scheduled_date + scheduled_interval.days)
  #   end
  #   "message sent : #{users.count}"
  # end

end

app/controllers/members_controller.rb
class MembersController < ApplicationController
  layout 'admin'
  before_action :authenticate_user!
  before_action :set_member, only: [:show, :edit, :update, :destroy]

  # GET /members
  # GET /members.json
  def index
    @members = current_user.members
  end

  # GET /members/1
  # GET /members/1.json
  def show
  end

  # GET /members/new
  def new
    @member = current_user.members.build
  end

  # GET /members/1/edit
  def edit
  end

  # POST /members
  # POST /members.json
  def create
    @member = Member.new(member_params)

    respond_to do |format|
      if @member.save
        format.html { redirect_to members_path, notice: 'Member was successfully created.' }
        format.json { render :show, status: :created, location: @member }
      else
        format.html { render :new }
        format.json { render json: @member.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /members/1
  # PATCH/PUT /members/1.json
  def update
    respond_to do |format|
      if @member.update(member_params)
        format.html { redirect_to members_path, notice: 'Member was successfully updated.' }
        format.json { render :show, status: :ok, location: @member }
      else
        format.html { render :edit }
        format.json { render json: @member.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /members/1
  # DELETE /members/1.json
  def destroy
    @member.destroy
    respond_to do |format|
      format.html { redirect_to members_url, notice: 'Member was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def import_csv
  end

  def import
   # binding.pry
    if params[:file]
      user_id = current_user.id
      members = Member.import(params[:file], user_id)
      if members
        redirect_to members_path, notice: 'CSV imported successfully'
      else
        redirect_to mass_sms_import_csv_path, notice: 'Invalid CSV'
      end
    else
      render :import_csv, notice: 'Please Select CSV file'
      # redirect_to mass_sms_import_csv_path, notice: 'Please Select CSV file'
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_member
      binding.pry

      @member = Member.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def member_params
      params.require(:member).permit(:name, :contact, :user_id)
    end
end

app/helpers/members_helper.rb
module MembersHelper
end

app/views/members/_form.html.erb
<%= form_for(@member,html: { class: "form-horizontal"}) do |f| %>
  <div class="form-group">
    <%= f.label "Name", class: "control-label col-xs-3"%>
    <div class="col-xs-6">
      <%= f.text_field :name, :class => "form-control",  placeholder: "Enter name"%>
    </div>  
  </div>
  
  <div class="form-group">
    <%= f.label "Contact", class: "control-label col-xs-3"%>
    <div class="col-xs-6">
      <%= f.text_field :contact, :class => "form-control",  placeholder: "Enter Contact"%>
    </div>  
  </div>

  <%= f.hidden_field :user_id, value: current_user.id %>

  <div class="text-center">
    <%= f.submit class: "btn btn-success" %>
  </div> <br>
<% end %>

app/views/members/_import_csv.html.erb
<%= form_tag import_members_path(current_user), multipart: true do %>
	<div class="form-group">
		<div class="col-xs-6">
				<%= file_field_tag :file, class: "control-label" %>
		</div>    
    <div class="col-xs-6">
			<%= submit_tag "Import CSV", class: "btn btn-success btn-sm"  %>
    </div> 
  </div>
<% end %>

app/views/members/edit.html.erb
<div class="box">
	<div class="box-header">
		<h3 class="box-title">Update Members</h3>
		<%= link_to 'New Member', new_member_path, style: "float: right", class: "btn btn-success btn-sm" %>
	</div>
	<div class="box-body no-padding users">
		<%= render 'form' %>
	</div>

app/views/members/import_csv.html.erb
<div class="box box-success">
	<div class="box-header">
		<h3 class="box-title">Add Members vis CSV</h3>
		<%= link_to 'All members', members_path, style: "float: right", class: "btn btn-success btn-sm" %>
	</div>
	<div class="box-body no-padding">
		<%= render 'import_csv' %>
		<br><br>
	</div>
</div>

<%# binding.pry %>

app/views/members/index.html.erb
<div class="box">
  <div class="box-header">
    <h3 class="box-title">Members</h3>
    <%= link_to 'New Member', new_member_path, style: "float: right", class: "btn btn-success btn-sm" %>
  </div>
  <div class="box-body no-padding users">
    <table class="table table-condensed">
      <thead>
        <tr>
          <th>Name</th>
          <th>Contact</th>
          <th colspan="2"></th>
        </tr>
      </thead>

      <tbody>
        <% @members.each do |member| %>
          <tr>
            <td><%= member.name %></td>
            <td><%= member.contact %></td>
            <!-- <td><%#= link_to 'Show', member %></td> -->
            <td><%= link_to 'Edit', edit_member_path(member), class: "badge bg-green" %></td>
            <!-- <td><%#= link_to 'Destroy', member, method: :delete, data: { confirm: 'Are you sure?' } %></td> -->
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/members/new.html.erb
<div class="box box-success">
	<div class="box-header">
		<h3 class="box-title">New Member</h3>
		<%= link_to 'All members', members_path, style: "float: right", class: "btn btn-success btn-sm" %>
	</div>
	<div class="box-body no-padding">
		<%= render 'form' %>
	</div>
</div>

app/views/members/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @member.name %>
</p>

<p>
  <strong>Contact:</strong>
  <%= @member.contact %>
</p>

<%= link_to 'Edit', edit_member_path(@member) %> |
<%= link_to 'Back', members_path %>